project:
  type: website
  output-dir: docs
  
website:
  title: "Gagan's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/gsingh91
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Gagandeep Singh"

format:
  html:
    theme: sketchy
    toc: true

editor: source

