project:
  type: website
  output-dir: docs
  
website:
  title: ""
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/gsingh91/website
          - text: Report an Issue
            url:  https://github.com/gsingh91/website/issues
    left:
      - href: index.qmd
        text: Home
      - talks.qmd
      - workshops.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) & Hosted on [GitHub](https://github.com/)"
    left: "&copy; Copyright 2023, Gagandeep Singh"

format:
  html:
    theme:
      dark: [solar, custom.scss]
      light: [flatly, custom-light.scss]
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center

editor: source

