project:
  type: website
  output-dir: docs
  
website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - talks.qmd
      - workshops.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) & Hosted on [GitHub](https://github.com/)"
    left: "&copy; Copyright 2023, Gagandeep Singh"

format:
  html:
    theme:
      dark: [solar, custom.scss]
      light: [flatly, custom-light.scss]
    toc: true

editor: source

